GET https://tabea-ketterer.herokuapp.com/addUrl?url=https%3A%2F%2Fi.pinimg.com%2F564x%2F7a%2Fff%2F9e%2F7aff9e3e3c32330d68d52184afdef645.jpg
###

GET https://tabea-ketterer.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/26/22/e4/2622e4966ef042a3ebe3680a03b87d2a.jpg

###

GET https://tabea-ketterer.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/72/32/15/7232151e25116cce4fc249dbdc12d667.jpg
###

GET https://tabea-ketterer.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/ef/60/24/ef60242859d2be3a92d10f0c4b7aec9d.jpg
###

GET https://tabea-ketterer.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/9b/33/d2/9b33d2f36220955b16dc1b40e864db47.jpg
###

GET https://tabea-ketterer.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/a1/23/d4/a123d4d299923637ed9eb03a93c88c6b.jpg
###

GET https://tabea-ketterer.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/c6/c2/38/c6c238759e1d9e16477d5e4fdfc3295d.jpg
###

GET https://tabea-ketterer.herokuapp.com/addUrl?url=https://i.pinimg.com/564x/b1/8d/2c/b18d2c3811107e6626ff179ac737acec.jpg

###
GET https://tabea-ketterer.herokuapp.com/getUrl
###
GET https://tabea-ketterer.herokuapp.com/getScores
###
GET https://tabea-ketterer.herokuapp.com/addScore?name=test23&time=1:24